### ISSUE TITLE
abstract-scheduler interface

### ISSUE THREAD

**Issue by derhuerst** [moll/js-square-batman#1]
I've just looked at scheduler npm packages and found this one to be exactly what I need. Thanks for this high-quality module!

I want to follow the example of [`abstract-chunk-store`](https://github.com/mafintosh/abstract-chunk-store), [`abstract-blob-store`](https://github.com/maxogden/abstract-blob-store) and [`abstract-point-store`](https://github.com/noffle/abstract-point-store) by introducing **`abstract-scheduler`, a standardised interface for schedules** like this one. Decoupling it from the actual implementations facilitates the creation of other compatible schedulers by the community. What do you think about the idea to make `js-square-batman` the first compatible implementation?

If you'd say yes, I'd have some proposals for the API of this package:

- Let's expose just one scheduler (`round-robin-scheduler` in this case) per package. Making them small an focused [has many benefits](https://gist.github.com/mafintosh/a3a99a23ea615d5bb015b5a3b9862c24#writing-great-modules).
- Let's rename `next()` to `get()` to make the interface more suitable for all kinds of schedulers. With some schedules you may actually get the same one again (e.g. a random scheduler).

**Comment by derhuerst** [comment]
FYI I've created [`abstract-scheduler`](https://github.com/derhuerst/abstract-scheduler) and written tests for it. It's not published to npm yet though.

**Comment by derhuerst** [comment]
Have built [`websocket-pool`](https://github.com/derhuerst/websocket-pool), which accepts a `abstract-scheduler`-compatible scheduler to load-balance messages over multiple websockets.

**Comment by derhuerst** [comment]
friendly ping (:

**Comment by derhuerst** [comment]
Have created [`round-robin-scheduler`](https://github.com/derhuerst/round-robin-scheduler) instead.

**Comment by moll** [comment]
Hi,

My bad for not responding quicker. I'm glad you went ahead without me being a blocker. :)

First, thanks for the compliment! Second, the some comments:

> Let's expose just one scheduler (round-robin-scheduler in this case) per package. Making them small an focused has many benefits.

I'm not too big of a fan of too small modules. It's the maintenance overhead both from the author and user's side that I dislike. I tend to review the source code of modules I use prior to using or upgrading them and the more different packages I have to go through, read commits and CHANGELOGs of, the more cumbersome it is. The world makes fun of the JavaScript's ecosystems' splitting of `is-number` (beyond the fact that it's wrapping `typeof foo == "number"`) for good reason in my op.

> Let's rename next() to get() to make the interface more suitable for all kinds of schedulers. With some schedules you may actually get the same one again (e.g. a random scheduler).

I don't remember exactly, but I believe I went with `next` over alternatives to match the iterator API. I should be able to do `for (foo of scheduler)` with Square Batman here and I think that's quite pleasing.

> I want to follow the example of abstract-chunk-store, abstract-blob-store and abstract-point-store by introducing abstract-scheduler, a standardised interface for schedules like this one. 

Finally, I'm not convinced an extra layer of abstraction solves any problems. The only abstraction I'd tolerate for recipients of schedulers (things that want "random" values) is probably the iterator API I mentioned above, or just a single function that returns the next value. Far less coupling. For the rest, I don't think there are many people that need to switch between so many different schedulers that they need multiple libs to conform to a single API. It's easier probably for everyone to write their own three lines of either a wrapper or scheduling functions than for us all to agree on an API. :P For example, I wrote mine to be a set from which values are grabbed and added to. You wrote yours as a vector (its `remove` method takes indices).

PS. The implementation you wrote is mutating the array given to its constructor. Warn people of that or fix it. Unexpected mutation of that sort is quite a dangerous thing.

**Comment by moll** [comment]
Your initial need for a shared interface (https://github.com/derhuerst/websocket-pool), I'd say, is better solved by a function (`createScheduler` in your README) that returns a function of random values, rather than a function that returns an object with a complex API. ;)

**Comment by derhuerst** [comment]
> I'm not too big of a fan of too small modules. It's the maintenance overhead both from the author and user's side that I dislike. I tend to review the source code of modules I use prior to using or upgrading them and the more different packages I have to go through, read commits and CHANGELOGs of, the more cumbersome it is.

This is a matter of taste I guess. I'd argue that look through documentation of larger/bloated libs is unnecessary overhead. 😉

> The world makes fun of the JavaScript's ecosystems' splitting of `is-number` (beyond the fact that it's wrapping `typeof foo == "number"`) for good reason in my op.

The point of libs like `is-number` is that it is *not* just `typeof foo == "number"`! Most people would expect a non-`NaN`, finite number. There are `Number.isFinite` and `Number.isNaN`, [but they are not supported everywhere](https://caniuse.com/#feat=es6-number). This is exactly the point: You don't have to memorise all these hidden weird behaviours by using `is-number`

I agree though that there's a degree of modularity where the overhead is not worth it anymore.

> Let's rename next() to get() to make the interface more suitable for all kinds of schedulers. With some schedules you may actually get the same one again (e.g. a random scheduler).
I don't remember exactly, but I believe I went with `next` over alternatives to match the iterator API. I should be able to do `for (foo of scheduler)` with Square Batman here and I think that's quite pleasing.

Nice idea!

`for of` loops use the Iterable API though (which is closely related to the Iterator API), which is not the same. An naive iterable `RoundRobin` would look like this:

```js
const {RoundRobin} = require('square-batman')

const roundRobin = new RoundRobin(['foo', 'bar'])
roundRobin[Symbol.iterator] = function* () {
    while (true) yield roundRobin.next()
}
for (let val of roundRobin) console.log(val)
```

> Finally, I'm not convinced an extra layer of abstraction solves any problems.

It's not exactly an abstraction. You can `npm install` and use every one of the compatible schedulers without worrying about the `abstract-scheduler` spec.

> The only abstraction I'd tolerate for recipients of schedulers (things that want "random" values) is probably the iterator API I mentioned above, or just a single function that returns the next value. Far less coupling.

There are recipients that would want to add/remove items from the pool. `websocket-pool` is a good example.

> For the rest, I don't think there are many people that need to switch between so many different schedulers that they need multiple libs to conform to a single API. It's easier probably for everyone to write their own three lines of either a wrapper or scheduling functions than for us all to agree on an API. :P

That's the "rewriting vs libraries" debate again. You can see in the mentioned `abstract-*` "ecosystems" that making them compatible drove innovation.

> For example, I wrote mine to be a set from which values are grabbed and added to. You wrote yours as a vector (its remove method takes indices).

Yeah, good point. The reason for that was to be able to use a primitive value (like `'foo'`) twice in the pool.

> PS. The implementation you wrote is mutating the array given to its constructor. Warn people of that or fix it. Unexpected mutation of that sort is quite a dangerous thing.

Good catch. Will adapt.

**Comment by moll** [comment]
> for of loops use the Iterable API though (which is closely related to the Iterator API), which is not the same. An naive iterable RoundRobin would look like this:

Ah right, I forgot `next` was supposed to return an object with a `value` and `done` fields. Yeah, my example definitely wouldn't work verbatim. Btw, I think most iterators return (or should return) themselves when considered iterable, and that's why I keep on using `for (x of foo)` with iterators. 

> There are recipients that would want to add/remove items from the pool. websocket-pool is a good example.

I actually think it'd be better if `websockets-pool` not be in the business of talking to scheduler APIs, exactly to both simplify _it_ and not require shared APIs other than a single function.

**Comment by derhuerst** [comment]
> Btw, I think most iterators return (or should return) themselves when considered iterable, and that's why I keep on using `for (x of foo)` with iterators.

First of all `for of` needs an iterable, not an iterator (guess you know that, just wanted to make it clear).

Don't think so actually. Most iterables return a *new* iterator on every `iterableThing[Symbol.iterator]()` call, so that you can iterate in parallel.

> I actually think it'd be better if `websockets-pool` not be in the business of talking to scheduler APIs, exactly to both simplify it and not require shared APIs other than a single function.

This would mean that consumers/users of `websocket-pool` would have to do the plumbing:

```js
const createScheduler = require('some-scheduler')
const createPool = require('websocket-pool')

const scheduler = createScheduler(['ws://foo', 'ws://bar'])
const getAddress = () => scheduler.get()

const onConnectionDown = url => scheduler.remove(url)
const onConnectionUp = url => scheduler.add(url)
const pool = createPool(scheduler, onConnectionDown, onConnectionUp)
```

While this is a bit more flexible, I've decided that it's not worth the more convoluted API surface. Most of the people won't care about the `scheduler` adding/removing. Those who do will be able to pass a custom `createScheduler` fn.

**Comment by moll** [comment]
> Don't think so actually. Most iterables return a new iterator on every iterableThing[Symbol.iterator]() call, so that you can iterate in parallel.

I was talking about iterators returning themselves when their iterator[Symbol.iterator] is called, which IMO makes using iterators convenient to use without their iterable available.  

> This would mean that consumers/users of websocket-pool would have to do the plumbing:

Umm, are you using the scheduler to store connections you've connected to or which connection to use next out of the ones you're connected to? You're initializing the scheduler with URLs in your example above --- that hints towards using the scheduler for URLs to connect to. For that, I don't think you need any mutation. You could just trust the `next` function to give you a URL and it's the scheduler's job to ensure uniqueness. From later callbacks, I'm leaning towards you intend to use two schedulers (based on the current REAMDE, with the requirement that both use the same algo), one for each. There indeed you need to add and remove connections (not only URLs, as the `createScheduler` function in the README names it).

**Comment by derhuerst** [comment]
> I was talking about iterators returning themselves when their iterator[Symbol.iterator] is called, which IMO makes using iterators convenient to use without their iterable available.

Watch out! It isn't `iterator[Symbol.iterator]`, but `iterable[Symbol.iterator]`. An iterable is an object that has a method at `Symbol.iterator` that returns an iterator.

But I get what you mean.

> Umm, are you using the scheduler to store connections you've connected to or which connection to use next out of the ones you're connected to? You're initializing the scheduler with URLs in your example above --- that hints towards using the scheduler for URLs to connect to. For that, I don't think you need any mutation.

I store all URLs that the `websocket-pool` is currently connected to. I need mutation because each of those connections may close at any time. It will try to open a new connection to the URL and, if successful, re-add the URL to the scheduler.

> You could just trust the `next` function to give you a URL and it's the scheduler's job to ensure uniqueness.

I don't necessarily want uniqueness. Or rather: If the scheduler's values were unique, they would have to have a weight instead.

**Comment by moll** [comment]
> I don't necessarily want uniqueness. Or rather: If the scheduler's values were unique, they would have to have a weight instead.

That kind of backs my argument that attempting to standardize on the level of a scheduler object rather than merely the "next" function is a poor idea --- that proposal doesn't accommodate any weighting or metadata for more general cases, for example. Anything more complex than random or round-robin is, after all, bespoke, dependent on a lot of contextual information and strongly coupled to its use-case and user. Therefore I don't see much value in attempting to generalize those APIs. If anything, I see it more having an inverse effect on the "innovation" platitude. ^_^

**Comment by derhuerst** [comment]
So what would you propose? because passing in a single function isn't going to be sufficient for real-world use cases.

**Comment by moll** [comment]
> > I was talking about iterators returning themselves when their iterator[Symbol.iterator] is called, which IMO makes using iterators convenient to use without their iterable available.
> 
> Watch out! It isn't `iterator[Symbol.iterator]`, but `iterable[Symbol.iterator]`. An iterable is an object that has a method at `Symbol.iterator` that returns an iterator.

I'm going through unanswered notifications and before I re-read what we were talking about here to reply to your last comment, I'll just mention that I think I was intentionally referring to `iterator[Symbol.iterator]` here. Having iterators return themselves permits using them in a `for (x of someIterator)`.

**Comment by derhuerst** [comment]
> I'll just mention that I think I was intentionally referring to `iterator[Symbol.iterator]` here. Having iterators return themselves permits using them in a `for (x of someIterator)`.

Yes, it allows you to loop over the *iterator* directly/itself, but this means that all loops over it will share the same results, which is unintuitive and IMO dangerous. Having each `[Symbol.iterator]()` call return a *new iterator* would prevent this. AFAIK the intended way is to loop over an *iterable*.

**Comment by moll** [comment]
> Yes, it allows you to loop over the *iterator* directly/itself, but this means that all loops over it will share the same results, which is unintuitive and IMO dangerous. Having each `[Symbol.iterator]()` call return a *new iterator* would prevent this.

Yeah, that's sensible — returning a _copy_ of the current iterator when calling its `Symbol.iterator` method. I'm all for more immutability. Although doing something like `first = it.next().value; for (var other of it) {}` and not have `it` pointing to the end could equally be surprising...

> AFAIK the intended way is to loop over an iterable.

You mean in a `for of` loop? Given that iterators are, I'd say, semantically iterable, passing iterators to  `for of` is congruent. ^_^

**Comment by derhuerst** [comment]
Just don't respond anymore in case you're not willing to continue this discussion about technical details. 😉

> Although doing something like first = it.next().value; for (var other of it) {} and not have it pointing to the end could equally be surprising...

But this is the common behaviour. If you iterate over an array via `for (const x of arr) {}`, you would expect the *next* `for` loop to start over.

> You mean in a `for of` loop? Given that iterators are, I'd say, semantically iterable, passing iterators to `for of` is congruent. ^_^

I disagree: The fact that [the built-in iterators *just happen to* return themselves](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-%iteratorprototype%-@@iterator) doesn't lead me to the conclusion that iterators and iterables are the same. In the example where a single iterable returns *several* iterators on repeated `[Symbol.iterator]()` calls, I think it becomes more obvious that they are two distinct semantic concepts.

Further sources:

- https://esdiscuss.org/topic/the-es6-iteration-protocol
- https://esdiscuss.org/topic/why-can-t-for-of-be-applied-to-iterators (probably outdated though, since it predates the final iteration spec)

**Comment by moll** [comment]
> Just don't respond anymore in case you're not willing to continue this discussion about technical details. :wink:

I'm sorry, I didn't get that. I thought we were talking about technical details. Aren't we? If you were referring to wanting to return to the original topic, then I've yet to re-read the thread, but promise to do so!

> > You mean in a `for of` loop? Given that iterators are, I'd say, semantically iterable, passing iterators to `for of` is congruent. ^_^
> 
> I disagree: The fact that [the built-in iterators _just happen to_ return themselves](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-%iteratorprototype%-@@iterator) doesn't lead me to the conclusion that iterators and iterables are the same. In the example where a single iterable returns _several_ iterators on repeated `[Symbol.iterator]()` calls, I think it becomes more obvious that they are two distinct semantic concepts.

I'm not saying iterators and iterables are indistinguishable nor that iterables are iterators. I am, though, claiming the inverse — that all iterators are iterables, especially semantically — an iterator, one could claim, is theoretically isomorphic to a lazily generated linked list, and a linked list surely is an iterable. 


> > Although doing something like first = it.next().value; for (var other of it) {} and not have it pointing to the end could equally be surprising...
> 
> But this is the common behaviour. If you iterate over an array via `for (const x of arr) {}`, you would expect the _next_ `for` loop to start over.

I would indeed expect the next loop to start over, but I'm not so sure I'd expect that a `for of` loop of an iterator would not advance the iterator. Precisely because I may want to use `for of` to implement an iterator utility function to pick _n_ items off of it. Secondly, it may not be possible to clone iterators, such as iterators from databases. As far as I can tell, `for of` ends up serving two purposes — to iterate over iterators, and, as syntactic sugar, convert iterables to iterators.

**Comment by derhuerst** [comment]
> I'm not saying iterators and iterables are indistinguishable nor that iterables are iterators. I am, though, claiming the inverse — that all iterators are iterables, especially semantically — an iterator, one could claim, is theoretically isomorphic to a lazily generated linked list, and a linked list surely is an iterable.

We can argue about this in two different ways: technically or semantics-wise.

Arguing technically, [iterators are *not* iterable by themselves](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-iterator-interface), except if they have [`%IteratorPrototype%`](https://www.ecma-international.org/ecma-262/9.0/index.html#sec-%iteratorprototype%-object) in their prototype chain (which all built-in iterators do). I can easily create one without: `{next: () => {done: true, value: undefined}`. This means that, in order to work with *any* valid iterator, implementations cannot expect iterators to be iterables.

Arguing semantically, I can see that this can be considered taste, but I see an *iterable* as something I can iterate/step/walk over and the *iterator* as the pointer/stepper.

> I would indeed expect the next loop to start over, but I'm not so sure I'd expect that a `for of` loop of an iterator would not advance the iterator.

When looping over an *iterable* (an array in our case), you would expect the next loop to start over. This is why it calls `[Symbol.iterator]()` again to get a *new iterator*. When iterating over an *iterator*, this assumption would fall apart. (As you noted, this is only true if the underlying data source allows it.)
